### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Zarkness2** [Fisher2911/Minions#3]
Hi, I just found this minions plugin and found it quite interesting and was wondering if you plan to continue it and also wondering if you have a discord group where you give support and if there is a way to test the plugin right now?

**Comment by Vulm** [comment]
https://discord.gg/VPctCk97Yr - The Discord Server.

Currently Fisher is somewhat inactive due to school, but he does his best to help and fix his plugins when he has time.

**Comment by Fisher2911** [comment]
I may continue it / start over at some point, but I asked in my discord and nobody really seemed interested.

**Comment by Zarkness2** [comment]
I am interested in using it, clearly if it has everything that jetsminions adds plus new things that I would like to suggest, since it has some pretty cool stuff that this plugin doesn't have. @Fisher2911

**Comment by Zarkness2** [comment]
if you want I can tell you what jetsminions has plus my suggestions.
